{
    "Outreach Display": "Sinclair's Outreach Display revolutionizes advertising with their extensive broadcast reach. It helps businesses connect with consumers efficiently through captivating news, entertainment, and sports content.",
    "Social Marketing": "Sinclair's Social Marketing employs its expertise in broadcasting to develop powerful social media campaigns. We utilize captivating content to engage customers effectively and improve brand visibility.",
    "YouTube Marketing": "Sinclair's YouTube Marketing service uses their broadcast influence to make effective video campaigns that promote brands well. They use their expertise in engaging news, entertainment, and sports content to maximize brand exposure and reach more people through targeted YouTube ads.",
    "Owned and Operated Display and Video": "Sinclair's Owned and Operated Display and Video services offer unparalleled control over advertising strategies. With a focus on leveraging owned media, they deliver compelling visual promotions on diverse third-party platforms, coupled with engaging video content marketing. Engage audiences effectively and drive brand recognition through tailored, dynamic advertising solutions.",
    "Branded Content": "Sinclair's Branded Content service helps businesses build strong and trusted relationships with their target audience by creating compelling and personalized stories that are seamlessly integrated with Sinclair's engaging news, entertainment, and sports content.",
}


[
    {"Primary Category": "Automobile - Dealers", "State": "TX", "Count": 101},
    {"Primary Category": "Automobile - Dealers", "State": "FL", "Count": 71},
    {"Primary Category": "Automobile - Dealers", "State": "CA", "Count": 69},
    {"Primary Category": "Automobile - Dealers", "State": "NC", "Count": 52},
    {"Primary Category": "Automobile - Dealers", "State": "NY", "Count": 49},
    {"Primary Category": "Automobile - Dealers", "State": "MI", "Count": 46},
    {"Primary Category": "Automobile - Dealers", "State": "PA", "Count": 43},
    {"Primary Category": "Automobile - Dealers", "State": "MD", "Count": 40},
    {"Primary Category": "Automobile - Dealers", "State": "OH", "Count": 37},
    {"Primary Category": "Automobile - Dealers", "State": "VA", "Count": 34},
    {"Primary Category": "Automobile - Dealers", "State": "GA", "Count": 32},
    {"Primary Category": "Automobile - Dealers", "State": "WA", "Count": 28},
    {"Primary Category": "Automobile - Dealers", "State": "IL", "Count": 24},
    {"Primary Category": "Automobile - Dealers", "State": "TN", "Count": 23},
    {"Primary Category": "Automobile - Dealers", "State": "WI", "Count": 22},
    {"Primary Category": "Automobile - Dealers", "State": "MN", "Count": 21},
    {"Primary Category": "Automobile - Dealers", "State": "NJ", "Count": 21},
    {"Primary Category": "Automobile - Dealers", "State": "AL", "Count": 20},
    {"Primary Category": "Automobile - Dealers", "State": "MO", "Count": 20},
    {
        "Primary Category": "Retirement & Assisted Living Facilities",
        "State": "TX",
        "Count": 19,
    },
    {"Primary Category": "Dentists", "State": "TX", "Count": 19},
    {"Primary Category": "Automobile - Dealers", "State": "SC", "Count": 18},
    {"Primary Category": "Dentists", "State": "CA", "Count": 18},
    {"Primary Category": "Automobile - Dealers", "State": "OK", "Count": 17},
    {"Primary Category": "Real Estate - Brokers & Agents", "State": "FL", "Count": 17},
    {
        "Primary Category": "Law - Personal Injury & Property Damage",
        "State": "CA",
        "Count": 17,
    },
    {
        "Primary Category": "Heating, Ventilation & Air Conditioning",
        "State": "FL",
        "Count": 17,
    },
    {"Primary Category": "Dentists", "State": "FL", "Count": 16},
    {"Primary Category": "Automobile - Dealers", "State": "CO", "Count": 16},
    {
        "Primary Category": "Law - Personal Injury & Property Damage",
        "State": "FL",
        "Count": 16,
    },
    {"Primary Category": "Automobile - Dealers", "State": "CT", "Count": 15},
    {"Primary Category": "Automobile - Dealers", "State": "IN", "Count": 15},
    {
        "Primary Category": "Heating, Ventilation & Air Conditioning",
        "State": "TX",
        "Count": 15,
    },
    {"Primary Category": "Automobile - Dealers", "State": "MA", "Count": 15},
    {"Primary Category": "Contractors - Computer", "State": "CA", "Count": 15},
    {"Primary Category": "Automobile - Dealers", "State": "LA", "Count": 14},
    {"Primary Category": "Automobile - Dealers", "State": "NV", "Count": 14},
    {"Primary Category": "Travel & Tourism", "State": "CA", "Count": 14},
    {"Primary Category": "Hotels, Motels, & Lodging", "State": "CA", "Count": 13},
    {"Primary Category": "Real Estate - Brokers & Agents", "State": "CO", "Count": 13},
    {"Primary Category": "Automobile - Dealers", "State": "AZ", "Count": 13},
    {"Primary Category": "Organizations & Associations", "State": "NY", "Count": 13},
    {"Primary Category": "Automobile - Repairs & Services", "State": "CA", "Count": 13},
    {
        "Primary Category": "Hospitals, Clinics & Medical Centers",
        "State": "FL",
        "Count": 13,
    },
    {"Primary Category": "Restaurants", "State": "CA", "Count": 12},
    {
        "Primary Category": "Law - Personal Injury & Property Damage",
        "State": "TX",
        "Count": 12,
    },
    {"Primary Category": "Organizations & Associations", "State": "FL", "Count": 12},
    {
        "Primary Category": "Contractors - Plumbers & Plumbing",
        "State": "CA",
        "Count": 11,
    },
    {"Primary Category": "Real Estate - Brokers & Agents", "State": "CA", "Count": 11},
    {"Primary Category": "Organizations & Associations", "State": "CA", "Count": 11},
    {"Primary Category": "Automobile - Dealers", "State": "AR", "Count": 11},
    {
        "Primary Category": "Heating, Ventilation & Air Conditioning",
        "State": "CO",
        "Count": 10,
    },
    {"Primary Category": "Contractors - Building", "State": "CA", "Count": 10},
    {"Primary Category": "Contractors - Roofing", "State": "FL", "Count": 9},
    {"Primary Category": "Automobile - Dealers", "State": "KS", "Count": 9},
    {
        "Primary Category": "Retirement & Assisted Living Facilities",
        "State": "FL",
        "Count": 9,
    },
    {"Primary Category": "Automobile - Dealers", "State": "KY", "Count": 9},
    {"Primary Category": "Hotels, Motels, & Lodging", "State": "TX", "Count": 9},
    {
        "Primary Category": "Physicians - Plastic & Cosmetic Surgery",
        "State": "FL",
        "Count": 9,
    },
    {
        "Primary Category": "Hospitals, Clinics & Medical Centers",
        "State": "CA",
        "Count": 9,
    },
]
