set5 = [
    "This set does not contain yes and no filters and only string output .",
    {
        "Signal Name": "Installed Apps",
        "Example Values": [
            "-",
            "WooCommerce Product Search",
            "Mailchimp Email SMS Marketing, Unlimited Bundles & Discounts, Sesami Booking App",
            "Square for WooCommerce",
            "Authorize.Net",
            "Mailchimp for WooCommerce",
            "Yotpo Reviews, Improved Layered Navigation",
            "Shopify Inbox, Product Reviews, Stape Server GTM",
            "AfterShip Email Marketing,SMS, PreCom ‑ coming soon preorders, HomeRoots Products Lister, Shopify Inbox",
            "Accessibility Enabler AW, Appstle℠ Loyalty & Rewards, Ilana's JSON‑LD for SEO (TM), Judge.me Product Reviews App, Klaviyo: Email Marketing & SMS, Linkify Product Colors, SC Product Options, Rebuy Personalization Engine, Searchanise Search & Filter, ShareASale, Appstle℠ Subscriptions App, Triple Whale",
            "Seguno",
            "Avada SEO Image Optimizer, Bundler ‑ Product Bundles, Gorgias: Helpdesk, Chat & FAQ, Ilana's JSON‑LD for SEO (TM), Klaviyo: Email Marketing & SMS, Shopify Planet, Product Reviews, Stamped Product Reviews & UGC, Warnify Pro Warnings, OC Quantity Breaks Order Limit, REVIEWS.io Product Reviews, Seal Subscriptions App, Sherpas: Smart SEO, Smile: Loyalty Rewards Program, Triple Whale, Warnify",
            "Agree Terms & Conditions PRO, Analyzely ‑ Google Analytics 4, Hextom: Countdown Timer Bar, FBP | Fast Bundle Product, Hulk Form Builder, Gift Box • Gift with Purchase, GOAFFPRO ‑ Affiliate Marketing, Google Reviews by Reputon, Instafeed ‑ Instagram Feed, Judge.me Product Reviews App, Klaviyo: Email Marketing & SMS, PageFly Landing Page Builder, Rebuy Personalization Engine, EPA‑ Easy Product Addons, POWr, Original Wheelio spin pop‑ups, Yoast SEO ‑ Store optimization",
            "Dr Volume & Bulk Discount, Analyzify (GA4 & Ads Tracking), Areviews ‑ Reviews Importer, Blocky: Fraud Filter Blocker, GO Product Page Gallery + Zoom, Mailchimp Email SMS Marketing, Minmaxify Order Limits, Product Reviews, Schema Plus for SEO & JSON‑LD, Shopify Forms, Variant Image Wizard + Swatch",
            "Easy Appointment Booking App, Fomo: Social Proof Sales Popup, Klaviyo: Email Marketing & SMS, PreOrder Globo | Back in Stock, Elfsight",
            "Affirm pay‑over‑time messaging, Omega Request Quote Hide Price, Elfsight, XO Gallery",
            "WooCommerce Deposits",
            "Affirm pay‑over‑time messaging, Attentive: SMS + MMS Marketing, Persistent Cart ‑ Sync Devices, Simprosys Google Shopping Feed, Happy Returns, a UPS Company, Gorgias: Helpdesk, Chat & FAQ, LFS Instant Brand Page, Kiwi Size Chart & Recommender, Klaviyo: Email Marketing & SMS, Locksmith, VerifyPass Community ID, Product Reviews, Route Protection and Tracking, Smart Wishlist",
            "Judge.me Product Reviews App, Unicorn Age Gate",
            "Infinite Options, Mailchimp",
            "WooCommerce Product Blocks",
            "WooCommerce Payments",
            "Affirm pay‑over‑time messaging, Powerful Contact Form Builder, Enorm Image gallery + Video, Klaviyo: Email Marketing & SMS, Loox ‑ Product Reviews App, Booster Page Speed Optimizer, PageFly Landing Page Builder, Globo Product Options, Variant",
            "Name Your Price",
            "Improved Layered Navigation",
            "Checkout Field Editor",
            "Drip",
            "AdRoll Marketing & Advertising, SEO:Image Optimizer Page Speed, Easy GDPR + Cookie Bar, Powerful Contact Form Builder, Growave: Loyalty & Wishlist, Improved Contact Form, Lucky Orange Heatmaps & Replay, Mailchimp: Email Marketing, Smart Search Bar & Filters, Store Pickup + Delivery (CR), S: Contact Form ‑ Contact Us, Wishlist Plus, Swym Back in Stock Alerts",
            "Printful: Print on Demand",
            "WooCommerce Cart Tab",
        ],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Shows the suite of apps, plugins, or integrations installed on the business’s website or online store, reflecting the level of automation, marketing sophistication, and customer experience enhancements in place.",
    },
    {
        "Signal Name": "Technologies - CMS",
        "Example Values": [
            "WordPress.org",
            "Bolt,Orchard CMS",
            "Joomla,DealerOn,Bolt",
            "sNews",
            "WordPress.org,Joomla,Squarespace,Bolt",
            "Bolt,Jarn,SiteEdit",
            "NextGuest Digital",
            "WordPress.org,Jazel",
            "WordPress.org,RnD Interactive",
            "Joomla,DealerOn,Bolt,sNews",
            "Drupal",
            "Orchard CMS",
            "Drupal,Acquia Platform",
            "Wix,Bolt,Jarn",
            "WordPress.org,Bolt",
            "Wix,Bolt",
            "WordPress.org,Wordpress.com",
            "Bolt,Eleanor CMS,Orchard CMS",
            "Squarespace",
            "Bolt",
            "Odoo",
            "Joomla",
            "Adobe Coldfusion",
            "Orchard CMS,sNews",
            "Joomla,Superlative,DealerOn,Reynolds and Reynolds,Bolt,sNews",
            "WordPress.org,Superlative",
            "Joomla,DealerOn,Reynolds and Reynolds,Bolt",
            "WordPress.org,Orchard CMS",
            "WordPress.org,Superlative,Bolt",
            "Bolt,Odoo",
            "Reynolds and Reynolds",
            "Salesforce Experience Cloud",
            "WordPress.org,sNews",
            "Drupal,Drupal, version 8",
            "Dealer Car Search",
            "Joomla,Superlative,Bolt",
            "WordPress.org,Amiro.CMS",
            "Superlative",
            "Joomla,Bolt",
            "WordPress.org,Joomla,Squarespace,Bolt,Orchard CMS",
            "SiteEdit",
            "WordPress.org,Eleanor CMS",
            "WordPress.org,Squarespace",
            "Evoq,DNN EVOQ",
            "WordPress.org,Wordpress.com,Bolt",
            "Craft CMS",
            "WordPress.org,Odoo",
            "WordPress.org,Salesforce Experience Cloud",
            "Joomla,Squarespace,Bolt",
            "Superlative,sNews",
            "WordPress.org,Joomla",
            "AutoRevo",
            "Evoq,DNN EVOQ,Bolt",
            "Salesforce Experience Cloud,Orchard CMS",
            "WordPress.org,Superlative,sNews",
            "Drupal,Salesforce Experience Cloud",
            "Eleanor CMS",
            "Bolt,Jarn",
            "WordPress.org,Odoo,Orchard CMS",
            "Bolt,sNews",
            "Craft CMS,Orchard CMS",
            "Bolt,Odoo,sNews",
            "WordPress.org,Wordpress.com,BuddyBoss",
            "Simpleview,Bolt",
            "WordPress.org,Odoo,sNews",
            "WordPress.org,MyCase",
            "SiteCore",
            "Drupal,Drupal, version 7",
            "Eleanor CMS,Orchard CMS",
            "WordPress.org,Simpleview",
            "WordPress.org,Wordpress.com,NetSuite",
            "Simpleview",
            "WordPress.org,Salesforce Experience Cloud,Orchard CMS",
            "NextGuest Digital,Orchard CMS,sNews",
            "Wix,Bolt,Jarn,SiteEdit",
            "Progress Sitefinity (formerly Telerik Sitefinity)",
            "Adobe Coldfusion,Bolt",
            "WordPress.org,Edlio CMS,Bolt",
            "Drupal,Acquia Platform,Bolt,Eleanor CMS,Orchard CMS",
            "WordPress.org,Hibu",
            "WordPress.org,Joomla,Bolt",
            "WordPress.org,Reynolds and Reynolds",
            "NetSuite,Craft CMS",
            "Drupal,Acquia Platform,Bolt,Eleanor CMS",
            "Squarespace,Salesforce Experience Cloud,SiteEdit",
            "WordPress.org,Bolt,sNews",
            "Drupal,Acquia Platform,Bolt",
            "Joomla,DealerOn,Bolt,Orchard CMS",
            "WordPress.org,Bolt,Orchard CMS",
            "WordPress.org,Squarespace,Bolt,Odoo,sNews,XOOPS",
            "NetSuite",
            "WordPress.org,Liferay",
            "WordPress.org,Textpattern CMS",
            "Joomla,DealerOn,Reynolds and Reynolds,Bolt,sNews",
            "WordPress.org,NetSuite",
            "WordPress.org,Joomla,DealerOn,Bolt",
            "Squarespace,Eleanor CMS",
            "Dealer Car Search,Promax",
            "WordPress.org,Craft CMS",
            "Edlio CMS",
            "WordPress.org,Martindale-Avvo",
            "Drupal,sNews",
            "Drupal,Orchard CMS",
            "WordPress.org,NextGuest Digital",
            "SiteCore,sNews",
            "Craft CMS,Bolt",
            "WordPress.org,Bolt,Eleanor CMS",
            "Joomla,Joomla 1.6",
            "WordPress.org,Adobe Coldfusion",
            "Simpleview,Bolt,Orchard CMS",
            "Amiro.CMS",
            "WordPress.org,Wordpress.com,Kolibri CMS",
            "WordPress.org,NetSuite,Evoq,DNN EVOQ",
            "WordPress.org,Orchard CMS,sNews",
            "WordPress.org,Reynolds and Reynolds,Bolt",
            "WordPress.org,Reynolds and Reynolds,Jazel",
            "WordPress.org,Wix,Bolt,Jarn,SiteEdit",
            "NetSuite,Bolt,Jarn,SiteEdit",
            "Drupal,Acquia Platform,Bolt,Orchard CMS",
            "WordPress.org,Progress Sitefinity (formerly Telerik Sitefinity)",
            "WordPress.org,BuddyBoss",
            "WordPress.org,Craft CMS,Bolt",
            "XOOPS",
            "Squarespace,sNews",
        ],
        "Description": "Lists the content management system(s) (CMS) powering the business website, such as WordPress, Joomla, or Squarespace. The CMS influences website capabilities, content publication, scalability, and integrations.",
    },
    {
        "Signal Name": "Technologies - Analytics and Tracking",
        "Example Values": [
            "Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics",
            "Google Analytics,Google Analytics 4 (GA4)",
            "VinLens,Google Analytics",
            "CrazyEgg,Google Analytics",
            "Google Analytics,Hotjar",
            "Google Analytics,Clicky,Google Analytics 4 (GA4)",
            "Google Analytics,Hotjar,Google Analytics 4 (GA4)",
            "Google Analytics,Matomo ,Google Analytics 4 (GA4)",
            "Google Analytics,Clicky",
            "CrazyEgg,Google Analytics,Canvas,AutoID",
            "VinLens,AutoID,Google Analytics",
            "Google Analytics,Telmetrics",
            "Hotjar,Google Analytics",
            "TruConversion,Google Analytics",
            "AutoID,Google Analytics",
            "Google Analytics,Gauges",
            "Google Analytics,MixPanel",
            "MouseFlow,Google Analytics",
            "Adobe,Google Analytics",
            "CrazyEgg,Google Analytics,Hotjar",
            "Google Analytics,Clicky,Inspectlet,Hotjar,AutoID",
            "CrazyEgg,Google Analytics,FullStory",
            "Google Analytics,Clicky,Hotjar",
            "Hotjar,FullStory,Google Analytics",
            "Google Analytics,Dataium",
            "CrazyEgg,Google Analytics,Adobe,Google Analytics 4 (GA4)",
            "Google Analytics,Clicky,AutoID",
            "Yahoo Analytics,Google Analytics 4 (GA4),Google Analytics",
            "Inspectlet,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,Clicky,Dataium",
            "MouseFlow,Google Analytics 4 (GA4),Google Analytics",
            "CrazyEgg,Google Analytics 4 (GA4),Google Analytics",
            "Hotjar,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,Hotjar,SOC 2 ",
            "Google Analytics,Gauges,Google Analytics 4 (GA4)",
            "CrazyEgg,Google Analytics,Google Analytics 4 (GA4)",
            "Google Analytics,VinLens",
            "Google Analytics,Inspectlet,Heatmap,Google Analytics 4 (GA4)",
            "Google Analytics,Matomo ",
            "Gauges,Google Analytics",
            "Telmetrics,Google Analytics",
            "Google Analytics,MixPanel,Google Analytics 4 (GA4)",
            "Hotjar,AutoID,Google Analytics",
            "FullStory,Google Analytics",
            "Google Analytics,MouseFlow,Google Analytics 4 (GA4)",
            "Google Analytics,Yahoo Analytics,VinLens",
            "Google Analytics,Yahoo Analytics",
            "CrazyEgg,Adobe,Google Analytics",
            "Google Analytics,Hotjar,ThomasNet Web Traxs",
            "CrazyEgg,Google Analytics,Telmetrics",
            "Google Analytics,Adobe,Hotjar",
            "ThomasNet Web Traxs,Google Analytics",
            "CrazyEgg,Google Analytics,Dataium",
            "Gauges,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,Yahoo Analytics,Google Analytics 4 (GA4)",
            "Yahoo Analytics,Google Analytics",
            "Google Analytics,Adobe",
            "CrazyEgg,Gauges,Google Analytics 4 (GA4),Google Analytics",
            "CrazyEgg,Google Analytics,Hotjar,Google Analytics 4 (GA4)",
            "MouseFlow,Hotjar,Google Analytics 4 (GA4),Google Analytics",
            "Hotjar",
            "Google Analytics,Inspectlet,Google Analytics 4 (GA4)",
            "SOC 2 ",
            "Telmetrics,Google Analytics 4 (GA4),Google Analytics",
            "SOC 2 ,Google Analytics",
            "Google Analytics,StatCounter",
            "MouseFlow,Inspectlet,Heatmap,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,MouseFlow",
            "Google Analytics,KISSmetrics,Google Analytics 4 (GA4)",
            "MixPanel,Google Analytics",
            "SOC 2 ,Google Analytics 4 (GA4),Google Analytics",
            "Woopra,Google Analytics",
            "OpenTracker,Google Analytics",
            "Google Analytics,Adobe,Dataium,AutoID",
            "Quantcast,Google Analytics",
            "Inspectlet,Hotjar,Google Analytics 4 (GA4),Google Analytics",
            "StatCounter,Google Analytics",
            "Google Analytics,Adobe,Google Analytics 4 (GA4)",
            "ThomasNet Web Traxs,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,Canvas,VinLens",
            "Google Analytics,ThomasNet Web Traxs",
            "Google Analytics,AutoID",
            "Google Analytics,Glassbox,Semcasting",
            "Google Analytics,StatCounter,Google Analytics 4 (GA4)",
            "Inspectlet,Google Analytics",
            "Google Analytics,Telmetrics,Google Analytics 4 (GA4)",
            "Google Analytics,ThomasNet Web Traxs,Hitslink,Google Analytics 4 (GA4)",
            "Google Analytics,Clicky,FullStory",
            "Quantcast,VinLens,Google Analytics",
            "Google Analytics,Inspectlet",
            "Glassbox,Google Analytics",
            "Google Analytics,Clicky,Canvas",
            "CrazyEgg,VinLens,AutoID,Google Analytics",
            "Hotjar,SOC 2 ,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,Hotjar,Gauges,Google Analytics 4 (GA4)",
            "Clicky,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,SOC 2 ",
            "FullStory,Google Analytics 4 (GA4),Google Analytics",
            "Matomo ,Google Analytics",
            "Matomo ,Google Analytics 4 (GA4),Google Analytics",
            "MixPanel,Google Analytics 4 (GA4),Google Analytics",
            "CrazyEgg,VinLens,Google Analytics",
            "CrazyEgg,Hotjar,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,Quantcast,Hotjar,Google Analytics 4 (GA4)",
            "Google Analytics,comScore,Parse.ly",
            "Clicky,Google Analytics",
            "ThomasNet Web Traxs,Hitslink,Google Analytics",
            "Quantcast,Google Analytics 4 (GA4),Google Analytics",
            "Clicky,Gauges,Google Analytics 4 (GA4),Google Analytics",
            "CrazyEgg,Google Analytics,ThomasNet Web Traxs",
            "Google Analytics,Quantcast",
            "Lucky Orange,Google Analytics",
            "Hotjar,Heatmap,Google Analytics",
            "StatCounter",
            "Adobe",
            "Yahoo Analytics,Telmetrics,Google Analytics 4 (GA4),Google Analytics",
            "Google Analytics,TruConversion,Google Analytics 4 (GA4)",
            "Google Analytics,ThomasNet Web Traxs,Google Analytics 4 (GA4)",
            "Yahoo Analytics,Inspectlet,Google Analytics",
            "Dataium,AutoID,Google Analytics",
            "CrazyEgg",
            "Chartbeat,Google Analytics",
            "CrazyEgg,Google Analytics,Clicky",
            "Google Analytics 4 (GA4)",
            "Google Analytics,Adobe,Telmetrics,Google Analytics 4 (GA4)",
            "CrazyEgg,Google Analytics,MixPanel",
        ],
        "Description": "Describes the analytics and user-tracking solutions in use (e.g., Google Analytics, Hotjar). These tools provide actionable insights into visitor behavior, website performance, and enable data-driven decision making for marketing and UX.",
    },
    {
        "Signal Name": "Website CMS",
        "Example Values": [
            "WordPress.org",
            "Bolt, Orchard CMS",
            "Joomla, DealerOn, Bolt",
            "sNews",
            "WordPress.org, Joomla, Squarespace, Bolt",
            "Bolt, Jarn, SiteEdit",
            "NextGuest Digital",
            "WordPress.org, Jazel",
            "WordPress.org, RnD Interactive",
            "Joomla, DealerOn, Bolt, sNews",
            "Drupal",
            "Orchard CMS",
            "Drupal, Acquia Platform",
            "Wix, Bolt, Jarn",
            "WordPress.org, Bolt",
            "Wix, Bolt",
            "WordPress.org, Wordpress.com",
            "Bolt, Eleanor CMS, Orchard CMS",
            "Squarespace",
            "Bolt",
            "Odoo",
            "Joomla",
            "Adobe Coldfusion",
            "Orchard CMS, sNews",
            "Joomla, Superlative, DealerOn, Reynolds and Reynolds, Bolt, sNews",
            "WordPress.org, Superlative",
            "Joomla, DealerOn, Reynolds and Reynolds, Bolt",
            "WordPress.org, Orchard CMS",
            "WordPress.org, Superlative, Bolt",
            "Bolt, Odoo",
            "Reynolds and Reynolds",
            "Salesforce Experience Cloud",
            "WordPress.org, sNews",
            "Drupal, Drupal, version 8",
            "Dealer Car Search",
            "Joomla, Superlative, Bolt",
            "WordPress.org, Amiro.CMS",
            "Superlative",
            "Joomla, Bolt",
            "WordPress.org, Joomla, Squarespace, Bolt, Orchard CMS",
            "SiteEdit",
            "WordPress.org, Eleanor CMS",
            "WordPress.org, Squarespace",
            "Evoq, DNN EVOQ",
            "WordPress.org, Wordpress.com, Bolt",
            "Craft CMS",
            "WordPress.org, Odoo",
            "WordPress.org, Salesforce Experience Cloud",
            "Joomla, Squarespace, Bolt",
            "Superlative, sNews",
            "WordPress.org, Joomla",
            "AutoRevo",
            "Evoq, DNN EVOQ, Bolt",
            "Salesforce Experience Cloud, Orchard CMS",
            "WordPress.org, Superlative, sNews",
            "Drupal, Salesforce Experience Cloud",
            "Eleanor CMS",
            "Bolt, Jarn",
            "WordPress.org, Odoo, Orchard CMS",
            "Bolt, sNews",
            "Craft CMS, Orchard CMS",
            "Bolt, Odoo, sNews",
            "WordPress.org, Wordpress.com, BuddyBoss",
            "Simpleview, Bolt",
            "WordPress.org, Odoo, sNews",
            "WordPress.org, MyCase",
            "SiteCore",
            "Drupal, Drupal, version 7",
            "Eleanor CMS, Orchard CMS",
            "WordPress.org, Simpleview",
            "WordPress.org, Wordpress.com, NetSuite",
            "Simpleview",
            "WordPress.org, Salesforce Experience Cloud, Orchard CMS",
            "NextGuest Digital, Orchard CMS, sNews",
            "Wix, Bolt, Jarn, SiteEdit",
            "Progress Sitefinity (formerly Telerik Sitefinity)",
            "Adobe Coldfusion, Bolt",
            "WordPress.org, Edlio CMS, Bolt",
            "Drupal, Acquia Platform, Bolt, Eleanor CMS, Orchard CMS",
            "WordPress.org, Hibu",
            "WordPress.org, Joomla, Bolt",
            "WordPress.org, Reynolds and Reynolds",
            "NetSuite, Craft CMS",
            "Drupal, Acquia Platform, Bolt, Eleanor CMS",
            "Squarespace, Salesforce Experience Cloud, SiteEdit",
            "WordPress.org, Bolt, sNews",
            "Drupal, Acquia Platform, Bolt",
            "Joomla, DealerOn, Bolt, Orchard CMS",
            "WordPress.org, Bolt, Orchard CMS",
            "WordPress.org, Squarespace, Bolt, Odoo, sNews, XOOPS",
            "NetSuite",
            "WordPress.org, Liferay",
            "WordPress.org, Textpattern CMS",
            "Joomla, DealerOn, Reynolds and Reynolds, Bolt, sNews",
            "WordPress.org, NetSuite",
            "WordPress.org, Joomla, DealerOn, Bolt",
            "Squarespace, Eleanor CMS",
            "Dealer Car Search, Promax",
            "WordPress.org, Craft CMS",
            "Edlio CMS",
            "WordPress.org, Martindale-Avvo",
            "Drupal, sNews",
            "Drupal, Orchard CMS",
            "WordPress.org, NextGuest Digital",
            "SiteCore, sNews",
            "Craft CMS, Bolt",
            "WordPress.org, Bolt, Eleanor CMS",
            "Joomla, Joomla 1.6",
            "WordPress.org, Adobe Coldfusion",
            "Simpleview, Bolt, Orchard CMS",
            "Amiro.CMS",
            "WordPress.org, Wordpress.com, Kolibri CMS",
            "WordPress.org, NetSuite, Evoq, DNN EVOQ",
            "WordPress.org, Orchard CMS, sNews",
            "WordPress.org, Reynolds and Reynolds, Bolt",
            "WordPress.org, Reynolds and Reynolds, Jazel",
            "WordPress.org, Wix, Bolt, Jarn, SiteEdit",
            "NetSuite, Bolt, Jarn, SiteEdit",
            "Drupal, Acquia Platform, Bolt, Orchard CMS",
            "WordPress.org, Progress Sitefinity (formerly Telerik Sitefinity)",
            "WordPress.org, BuddyBoss",
            "WordPress.org, Craft CMS, Bolt",
            "XOOPS",
            "Squarespace, sNews",
        ],
        "Description": "Shows the specific content management system used for the company's website, which impacts everything from web design to extensibility, digital marketing, and maintenance requirements.",
    },
]


set2 = [
    "This is a set for social media, website design and seo related help. Nothing else like ads or social media. Aything related to these things in search query focus on it",
    {
        "Signal Name": "Website Page Count",
        "Example Values": ["34", "20", "226", "26", "114"],
        "Description": "Indicates how many unique pages the company's website contains. A larger page count often means more comprehensive information, product offerings, SEO depth, or content marketing activity.",
    },
    {
        "Signal Name": "Mobile Friendly",
        "Example Values": ["Yes"],
        "Description": "Mobile-friendliness of a website refers to its ability to display and function correctly on both desktop/laptop computers and mobile devices such as phones or tablets, offering user-friendly navigation, readable text, easily clickable links, and responsive layouts that adapt seamlessly to different screen sizes. A mobile-friendly website not only enhances overall user experience and engagement, but is also a key factor in boosting search engine rankings (SEO) and ensuring broad accessibility for customers on the go. This signal is critical: if there are any issues related to website usability, poor design, technical faults, or subpar performance—especially on mobile devices—these can directly drive away visitors, harm brand reputation, and reduce conversion rates. For any business, monitoring and optimizing mobile-friendliness should be a high priority when evaluating website-related data or addressing digital presence concerns.",
    },
    {
        "Signal Name": "SEO Score",
        "Example Values": [95, 100, 90, 86, 81],
        "Description": "Reports the website's search engine optimization score, evaluating how well it adheres to SEO best practices. Higher scores signify better chances of organic search visibility and online lead generation.",
    },
    {
        "Signal Name": "Trust Flow",
        "Example Values": ["1", "11", "35", "37", "22"],
        "Description": "Supplies a measure of the business website's trustworthiness and authority, based on backlink quality (a ‘Majestic’ SEO metric). High trust flow indicates established brand credibility and domain value.",
    },
    {
        "Signal Name": "Local Presence",
        "Example Values": ["Yes", "No", "-"],
        "Description": "Tells whether the business operates within a defined local or regional area. Local presence strengthens local SEO, word-of-mouth marketing, and personalized services.",
    },
    {
        "Signal Name": "Domain Age",
        "Example Values": ["13Y, 7M", "26Y, 1M", "28Y, 10M", "12Y, 5M", "27Y, 7M"],
        "Description": "Indicates the number of years and months the main business website's domain has been active. Older domains are often trusted more by both search engines and consumers.",
    },
    {
        "Signal Name": "Social Score",
        "Example Values": [100, 94, 88, 82, 76],
        "Description": "A holistic index reflecting the strength, engagement, size, and influence of the business's social media activities across all platforms.",
    },
    {
        "Signal Name": "Facebook Business Page",
        "Example Values": ["Yes"],
        "Description": "Specifies if the business has an official Facebook page to promote products, interact with customers, and run social campaigns—fundamental for building community and social proof.",
    },
    {
        "Signal Name": "Facebook Likes",
        "Example Values": ["1,230", "112", "4,292", "2,394", "1,898"],
        "Description": "Indicates how many users have liked or followed the company's Facebook page, representing its popularity and digital reach on the world's largest social network.",
    },
    {
        "Signal Name": "Facebook Check-ins",
        "Example Values": ["76", "7", "1,517", "9,658", "2,228"],
        "Description": "Shows the number of times people have physically checked in at the business location on Facebook, offering social proof and helping evaluate customer foot traffic.",
    },
    {
        "Signal Name": "X (Formerly Twitter) Business Account",
        "Example Values": ["Yes", "No"],
        "Description": "Reveals whether the business maintains a presence on X (formerly Twitter), a key channel for real-time updates, customer engagement, and brand communication.",
    },
    {
        "Signal Name": "X (Formerly Twitter) Followers",
        "Example Values": ["2", "33", "722", "73", "-"],
        "Description": "Provides the total follower count on X/Twitter, helping to estimate the business’s social influence and audience dimension in that channel.",
    },
    {
        "Signal Name": "Posts",
        "Example Values": ["135", "9", "2,318", "251", "-"],
        "Description": "Captures the total number of posts, tweets, updates, or entries shared by the business across social/media channels. Frequent posts typically indicate active engagement with audiences.",
    },
    {
        "Signal Name": "YouTube Channel",
        "Example Values": ["Yes", "No"],
        "Description": "Shows if the business operates an official YouTube channel, leveraging video content for branding, demonstrations, customer education, and inbound marketing.",
    },
    {
        "Signal Name": "LinkedIn Company Page",
        "Example Values": ["Yes", "No", "-"],
        "Description": "States whether the company maintains a LinkedIn page to support business-to-business networking, recruiter engagement, and corporate brand building online.",
    },
    {
        "Signal Name": "Pinterest Business Account",
        "Example Values": ["Yes", "No", "-"],
        "Description": "Indicates if the business runs a Pinterest profile, usually used for content discovery in highly visual industries such as retail, design, and events.",
    },
    {
        "Signal Name": "Pinterest Followers",
        "Example Values": ["-", "0", "20", "158", "54"],
        "Description": "Reflects the current follower count of the company's Pinterest account, conveying the scope of its visual content network and outreach.",
    },
    {
        "Signal Name": "Pinterest Following",
        "Example Values": ["-", "0", "55", "3", "5"],
        "Description": "Provides the number of other Pinterest profiles or boards the business is following, possibly indicating partnerships, market monitoring, or influencer outreach.",
    },
    {
        "Signal Name": "Pinterest Pins",
        "Example Values": ["-", "7", "72", "5", "0"],
        "Description": "The total posts (pins) the business has shared on Pinterest, typically a good measure of active participation and visual marketing effort.",
    },
    {
        "Signal Name": "Pinterest Boards",
        "Example Values": ["-", "4", "13", "2", "0"],
        "Description": "The number of boards (collections/categories) managed by the business on Pinterest, providing insight into their organizational and marketing themes.",
    },
    {
        "Signal Name": "Pinterest Domain Verified",
        "Example Values": ["No", "-", "Yes"],
        "Description": "Indicates if the business's domain is verified on Pinterest, boosting content credibility and unlocking analytic and promotional features.",
    },
    {
        "Signal Name": "Pinterest Verified Merchant",
        "Example Values": ["No", "-", "Yes"],
        "Description": "Shows if the business is a verified merchant on Pinterest—a mark of trust and authenticity for customers shopping or engaging with content.",
    },
    {
        "Signal Name": "Instagram Business Account",
        "Example Values": ["Yes", "No", "-"],
        "Description": "Specifies whether the company runs an Instagram business profile, unlocking analytics, advertising tools, and more robust branding features for visual marketing.",
    },
    {
        "Signal Name": "Instagram Posts",
        "Example Values": ["135", "1", "1,434", "1,032", "1,067"],
        "Description": "Shows the total number of posts or stories published on the company's Instagram profile. High volume suggests an active, engaged visual channel.",
    },
    {
        "Signal Name": "Instagram Followers",
        "Example Values": ["257", "6", "7,881", "22,263", "894"],
        "Description": "Indicates the number of Instagram followers for the business, suggesting its brand visibility and influence in highly visual marketplaces.",
    },
    {
        "Signal Name": "Instagram Following",
        "Example Values": ["172", "0", "95", "7,446", "6,102"],
        "Description": "States how many other profiles the business follows on Instagram, which can hint at trends, partnerships, or market segments of interest.",
    },
]
set4 = [
    "This set is mostly relaetd to E commerce related signals",
    {
        "Signal Name": "Scheduler",
        "Example Values": ["Yes", "No"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Scheduler features enable customers to book appointments, services, or meetings online, streamlining the customer journey and lowering administrative workload while improving service accessibility.",
    },
    {
        "Signal Name": "Premium Calculator",
        "Example Values": ["No", "Yes"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Premium Calculators are interactive tools commonly used by financial services, insurance, or real estate businesses, allowing customers to estimate loan premiums, mortgage payments, or refinancing costs directly from the website.",
    },
    {
        "Signal Name": "Inventory Tracking",
        "Example Values": ["No", "Yes"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Inventory Tracking enables both customers and business staff to monitor product availability in real time, reducing overselling, improving user trust, and assisting with supply chain management.",
    },
    {
        "Signal Name": "Finance",
        "Example Values": ["No", "Yes"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Finance features offer options like installment payments, credit, or pre-approval, helping customers afford larger purchases while increasing conversion rates and average order value for the business.",
    },
    {
        "Signal Name": "WishList",
        "Example Values": ["No", "Yes", "-"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. The Wishlist feature allows shoppers to bookmark products for future purchases, encourages return visits, and provides valuable insight into demand and trending items for inventory planning.",
    },
    {
        "Signal Name": "Order Tracking",
        "Example Values": ["No", "Yes", "-"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Order Tracking lets customers monitor the progress and delivery status of their purchases, which increases transparency, decreases support requests, and improves post-purchase satisfaction.",
    },
    {
        "Signal Name": "Get A Quote",
        "Example Values": ["Yes", "No"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Get A Quote tools enable customers to request personalized pricing for products or services, particularly for high-value, customized, or bulk purchases, assisting with lead generation and sales pipeline management.",
    },
    {
        "Signal Name": "Estimate Page",
        "Example Values": ["Yes", "No"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. An Estimate Page lets customers calculate price ranges or receive preliminary quotes for services or products, making it easier to qualify leads and speed up the sales cycle.",
    },
    {
        "Signal Name": "FB Shop",
        "Example Values": ["No", "-", "Yes"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Facebook Shop integration allows the business to list, promote, and sell products directly through Facebook’s commerce ecosystem, expanding sales channels and reaching social shoppers.",
    },
    {
        "Signal Name": "Amazon Seller",
        "Example Values": ["No", "-", "Yes"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. 'Amazon Seller' means the business is officially listed as a merchant on the Amazon marketplace, giving access to a huge customer base and leveraging Amazon’s logistics and trust.",
    },
    {
        "Signal Name": "Monthly App Spend",
        "Example Values": ["-", "$1K - $5K", "$0 - $1K", "$50K - $100K", "$5K - $20K"],
        "Description": "This is an e-commerce signal. E-commerce refers to the buying and selling of goods or services using the internet. Indicates the business's recurring monthly expenditure on applications, integrations, or SaaS tools, highlighting the scale of its digital operations and commitment to technology.",
    },
]


set3 = [
    "This signal is related to ads and advertisement and apps. Not social media accounts",
    {
        "Signal Name": "Android App",
        "Example Values": ["No", "Yes"],
        "Description": "States whether the business offers an official app for Android devices. This enables direct mobile engagement, loyalty program access, and facilitates digital sales or customer interactions.",
    },
    {
        "Signal Name": "iOS App",
        "Example Values": ["No", "Yes"],
        "Description": "Indicates whether the business has developed an app for Apple/iOS users, enabling more secure and seamless access to business services from iPhones and iPads.",
    },
    {
        "Signal Name": "Advertising Score",
        "Example Values": [41, 46, 51, 61, 56],
        "Description": "Presents a numeric or categorical representation of the business’s advertising reach, investment, and overall effectiveness. A higher advertising score suggests more active, visible, and possibly diverse promotional efforts that can drive customer acquisition and brand recognition.",
    },
    {
        "Signal Name": "Google Ads Presence",
        "Example Values": ["No", "Yes", "-"],
        "Description": "Indicates whether the business is actively running paid advertisements on Google Ads. This not only affects web traffic and lead generation but also signals a commitment to digital advertising strategies.",
    },
    {
        "Signal Name": "Google AdWords Cost",
        "Example Values": ["0", "<$1K", "$1K - $5K", "$50K - $100K", "-"],
        "Description": "Represents the estimated budget or spending range allocated by the business on Google AdWords campaigns. Higher costs often reflect competitive sectors, ambitious marketing goals, and significant customer acquisition efforts.",
    },
    {
        "Signal Name": "Google Ads Traffic",
        "Example Values": ["0", "29", "1", "2", "6"],
        "Description": "Measures the number of leads or visitors driven to the company’s website from Google Ads. Greater traffic from ads usually points to well-targeted campaigns and effective ad spending.",
    },
    {
        "Signal Name": "Display Ads",
        "Example Values": ["No", "Yes", "-"],
        "Description": "Reveals if the business employs display advertising (banner, image, or interactive ads) across the web. Display ads increase brand awareness, support retargeting, and can drive new customer engagement outside of search channels.",
    },
    {
        "Signal Name": "Facebook Ads",
        "Example Values": ["No", "Yes", "-"],
        "Description": "Shows whether the company runs paid advertising campaigns on Facebook. Facebook ads broaden reach to targeted audiences, and their success can massively influence online sales and brand perception.",
    },
    {
        "Signal Name": "HomeAdvisor - Advertising",
        "Example Values": ["Yes", "-", "No"],
        "Description": "Indicates if the business invests in paid listings or advertisements on HomeAdvisor, a service that helps acquire local leads and home service customers.",
    },
    {
        "Signal Name": "ThumbTack - Advertising",
        "Example Values": ["No", "Yes"],
        "Description": "Shows whether the business is using paid advertising on Thumbtack to boost service listings, gain more leads, and enhance visibility in local service search results.",
    },
]

set1 = [
    {
        "Signal Name": "Peak Sales Month",
        "Example Values": [
            "Apr, Jul",
            "Mar, Apr, May, Sep, Oct, Nov",
            "Jan, Feb, Mar",
            "Jun, Jul, Aug",
            "Mar, Jun, Jul, Aug",
            "Apr, May, Jul, Dec",
            "Oct, Nov, Dec",
            "Sep, Nov, Dec",
            "Jul, Aug, Sep",
            "Jan, Feb",
            "Jan, Apr, Oct, Nov, Dec",
            "Jan, Mar, Jun, Aug",
            "Feb, Mar, Aug",
        ],
        "Description": "Represents the period(s) of the year when the business experiences the highest sales volumes. This information reveals seasonality trends and helps identify optimal times for campaigns, inventory planning, and resource allocation.",
    },
    {
        "Signal Name": "Avg Revenue/Business",
        "Example Values": [
            "$833.03k",
            "$38979.62k",
            "$324.16k",
            "$1237.68k",
            "$378.59k",
            "$0.00k",
        ],
        "Description": "Shows the average annual or monthly revenue generated by the business, providing an essential benchmark for understanding business scale, growth, and market performance.",
    },
    {
        "Signal Name": "Locations Count",
        "Example Values": ["1", "2", "3", "25", "9"],
        "Description": "Displays the total number of physical or operational locations (stores, offices, branches, or service points) a business maintains. A higher number usually indicates broader reach and potential for regional or national operations.",
    },
    {
        "Signal Name": "Business Type",
        "Example Values": ["Commercial", "-", "Residential"],
        "Description": "Specifies the operational focus of the company, such as Commercial, Residential, or other segments. Knowing this helps determine business priorities, target markets, and product/service offerings.",
    },
    {
        "Signal Name": "Annual Revenue",
        "Example Values": [
            "$2.5M - $5M",
            "$50M - $100M",
            "$500K - $1M",
            "$1M - $2.5M",
            "$10M - $25M",
        ],
        "Description": "Presents the estimated total annual earnings the business generates within a fiscal year. This financial metric is critical for assessing business maturity, potential, and risk.",
    },
    {
        "Signal Name": "Tech Spend/month",
        "Example Values": ["$0 - $1K", "$5K - $20K", "$1K - $5K", "-", "$20K - $50K"],
        "Description": "Represents the estimated or reported monthly investment the company makes in technology—including software, hardware, cloud platforms, and IT services. Monitoring this helps evaluate the digital maturity and capability of a business.",
    },
    {
        "Signal Name": "Business Age",
        "Example Values": ["-", ">10Y", "6Y - 10Y", "3Y - 5Y", "1Y"],
        "Description": "Shows how long the business has been in operation (in years). Older businesses often have more market experience and brand equity, while newer ones may reflect innovation or rapid growth.",
    },
    {
        "Signal Name": "Business Model",
        "Example Values": ["B2B", "B2C", "B2B & B2C", "-"],
        "Description": "Clarifies the method by which a business delivers value, typically as B2B (business to business), B2C (business to consumer), both, or other. This helps shape sales strategies, customer acquisition, and product development efforts.",
    },
    {
        "Signal Name": "Remote-Only Business",
        "Example Values": ["No", "Yes"],
        "Description": "Indicates if the company operates exclusively online, with no brick-and-mortar footprint. Remote-only businesses typically invest heavily in digital infrastructure and serve markets beyond physical location limits.",
    },
    {
        "Signal Name": "Google My Business - Listed",
        "Example Values": ["Yes", "-", "No"],
        "Description": "Indicates if the business has a verified profile on Google My Business, improving its visibility in search results and Google Maps. This is crucial for local customer discovery and reputation management.",
    },
    {
        "Signal Name": "Google My Business - Claimed",
        "Example Values": ["Yes", "-", "No"],
        "Description": "Shows whether the business owner actively manages their verified Google My Business profile. Claimed profiles allow for updating business info, responding to reviews, and posting updates, impacting local SEO.",
    },
    {
        "Signal Name": "Google Reviews",
        "Example Values": ["Yes", "-", "No"],
        "Description": "Signifies whether the business receives and displays customer reviews on Google. Such reviews influence search rankings, credibility, and customer conversion rates.",
    },
    {
        "Signal Name": "Google Reviews Count",
        "Example Values": ["346", "12", "23", "148", "1622"],
        "Description": "Displays the total number of customer reviews about the business on Google. A higher count not only boosts trust but also improves business ranking in search results.",
    },
    {
        "Signal Name": "Google Rating",
        "Example Values": ["4.8", "4", "3.6", "4.3", "4.6"],
        "Description": "Shows the average star rating (from 1 to 5) the business has earned on Google based on user feedback. High ratings bolster credibility and drive more customer inquiries and conversions.",
    },
    {
        "Signal Name": "Nextdoor",
        "Example Values": ["Yes", "No"],
        "Description": "Shows if the business maintains an active presence on Nextdoor, a hyperlocal social network. This presence is valuable for fostering trust, engaging with community members, and driving word-of-mouth referrals.",
    },
    {
        "Signal Name": "Nextdoor_Recommendation",
        "Example Values": ["25", "-", "2", "5", "3"],
        "Description": "The number of positive customer recommendations received on Nextdoor. High recommendations typically indicate excellent local reputation and strong community engagement.",
    },
    {
        "Signal Name": "Nextdoor_License",
        "Example Values": [
            "-",
            "820045",
            "IICRC 029350",
            "#99",
            "PA # 013083",
            "PC11003362",
            "Contractor ID: 1127911 Wisconsin Contractor License",
            "30218",
            "Lic. 217132",
            "CC#18-GD-21226-X",
            "135891",
            "146472",
            "25973",
            "Lic. CT 0556507 | MA 176974",
            "LICENSE # 850093",
            "CFC1428537",
            "1357367",
            "501163",
            "Lic. Arizona K-34 #251484",
            "Lic. KY 7105",
            "Lic. CSLB Lic #847973",
            "Lic. 21070T",
            "PA012126",
            "01054310",
            "Lic. AY1803 and AY1962",
            "TACLA 92943C",
            "ROC 085902, ROC 093021, ROC 102736, ROC 262385",
            "0225221820",
            "ID License #57670 WA License #96366",
            "Lic. iicrc6945766",
        ],
        "Description": "Reflects any license or credential the business presents on Nextdoor, giving confidence in regulatory compliance and professionalism.",
    },
    {
        "Signal Name": "Nextdoor_Neighborhood Favorite",
        "Example Values": ["Yes", "-", "No"],
        "Description": "Specifies whether the business has been recognized as a Neighborhood Favorite on Nextdoor. This badge signals strong local support and customer loyalty.",
    },
    {
        "Signal Name": "Employee Size",
        "Example Values": [
            "1 to 10",
            "11 to 50",
            "501 to 1000",
            "201 to 500",
            "51 to 100",
        ],
        "Description": "Estimates the number of employees in the business. Employee scale can imply operational capacity, market reach, and likely business complexity.",
    },
    {
        "Signal Name": "Review(s)",
        "Example Values": ["0", "-", "9", "3", "15"],
        "Description": "Reports the aggregate number of reviews or testimonials across all platforms, giving an overarching measure of customer feedback and engagement.",
    },
    {
        "Signal Name": "Ratings",
        "Example Values": ["0", "-", "3.2", "4.0", "3.8"],
        "Description": "Displays the average customer rating drawn from all available reviews. This summary rating reflects overall satisfaction and service quality.",
    },
]
